# Generated by Django 5.1.4 on 2025-05-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason_type',
            field=models.CharField(choices=[('SPAM', '불법광고'), ('ABUSE', '욕설/인신공격'), ('REPEAT', '도배성글/댓글반복'), ('PRIVACY', '개인정보노출/사생활침해'), ('SEXUAL', '음란성/선정성'), ('FALSE_INFO', '허위정보/가짜리뷰'), ('DISCRIMINATION', '차별/혐오표현'), ('ETC', '기타부적절한행위')], max_length=50),
        ),
    ]
