# Generated by Django 5.1.5 on 2025-02-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('ADMIN', 'Admin'), ('NORMAL', 'Normal'), ('SUBSCRIBE', 'Subscribe')], default='NORMAL', max_length=64)),
            ],
            options={
                'db_table': 'account_role_type',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=32)),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountroletype')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
