# Generated by Django 5.1.4 on 2025-04-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_path',
            field=models.CharField(blank=True, choices=[('kakao', 'Kakao'), ('naver', 'Naver'), ('google', 'Google'), ('meta', 'Meta'), ('us', 'Us')], max_length=10, null=True),
        ),
    ]
