
# Generated by Django 5.1.7 on 2025-05-12 17:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_account_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.AddField(
            model_name='account',
            name='account_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='banned_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
