# Generated by Django 5.1.4 on 2025-04-17 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_account_account_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPrefer',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('Q_1', models.TextField(blank=True, null=True)),
                ('Q_2', models.TextField(blank=True, null=True)),
                ('Q_3', models.TextField(blank=True, null=True)),
                ('Q_4', models.TextField(blank=True, null=True)),
                ('Q_5', models.TextField(blank=True, null=True)),
                ('Q_6', models.TextField(blank=True, null=True)),
                ('Q_7', models.TextField(blank=True, null=True)),
                ('Q_8', models.TextField(blank=True, null=True)),
                ('Q_9', models.TextField(blank=True, null=True)),
                ('Q_10', models.TextField(blank=True, null=True)),
                ('Q_11', models.TextField(blank=True, null=True)),
                ('Q_12', models.TextField(blank=True, null=True)),
                ('Q_13', models.TextField(blank=True, null=True)),
                ('Q_14', models.TextField(blank=True, null=True)),
                ('Q_15', models.TextField(blank=True, null=True)),
                ('Q_16', models.TextField(blank=True, null=True)),
                ('Q_17', models.TextField(blank=True, null=True)),
                ('Q_18', models.TextField(blank=True, null=True)),
                ('Q_19', models.TextField(null=True, blank=True)),
                ('Q_20', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account_prefer',
            },
        ),
    ]
