# Generated by Django 5.1.4 on 2025-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='alarm_board_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='alarm_comment_status',
            field=models.BooleanField(default=True),
        ),
    ]
