# Generated by Django 5.1.4 on 2025-04-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delete_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deletedaccount',
            table='delete_account',
        ),
    ]
