# Generated by Django 5.1.7 on 2025-04-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_category_restaurant_closed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='closed',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
    ]
