# Generated by Django 5.1.7 on 2025-05-10 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_profile', '0001_initial'),
        ('restaurants', '0003_remove_restaurant_image_alter_restaurant_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountScrap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_profile.accountprofile')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'account_scrap',
                'unique_together': {('restaurant', 'author')},
            },
        ),
    ]
